INSERT INTO roles(name) VALUES ('ADMIN');
INSERT INTO roles(name) VALUES ('SELLER');
INSERT INTO roles(name) VALUES ('BUYER');

-- User mock data (size 50)
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Faustina', 'Skillings', 'fskillings0@domainmarket.com', 'qMQ34mF', 2);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Leda', 'Crush', 'lcrush1@indiatimes.com', 'NwF8annKFa1', 3);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Sissie', 'Hoodspeth', 'shoodspeth2@home.pl', 'nAQ1Ithdfd', 3);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Johann', 'Souness', 'jsouness3@tripod.com', 'nDrp4dyUwW', 3);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Burl', 'Laetham', 'blaetham4@ucoz.com', 'uso10LeS', 2);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Teddy', 'Hatliff', 'thatliff5@moonfruit.com', 'fAwq84rXQ7', 1);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Peterus', 'von Hagt', 'pvonhagt6@blogspot.com', 'G75VvhCwa', 2);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Clo', 'Najara', 'cnajara7@skyrock.com', 'd16VV5H0Egaz', 3);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Carlynne', 'Stanners', 'cstanners8@nba.com', '2y1tcWkmEp2', 2);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Aurea', 'Schubert', 'aschubert9@cargocollective.com', '3xm68JZF7', 2);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Cullan', 'MacCart', 'cmaccarta@csmonitor.com', 'JogtEnK', 2);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Thomasine', 'Isacq', 'tisacqb@theguardian.com', 'keD9jz', 2);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Nickolai', 'Hinkins', 'nhinkinsc@jugem.jp', '7GkFVRGoa', 1);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Bendick', 'Hastewell', 'bhastewelld@weebly.com', 'DS5d8tHwuR', 1);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Heather', 'Tunsley', 'htunsleye@wikispaces.com', 'wT9CX5KH', 3);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Deeann', 'Stockney', 'dstockneyf@51.la', 'chHzQD', 1);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Willis', 'Bellwood', 'wbellwoodg@upenn.edu', '8jHCSXd', 2);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Thornton', 'Brook', 'tbrookh@ning.com', 'KcGOAfPcsQPP', 2);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Delmar', 'O''Lenechan', 'dolenechani@umn.edu', 'sb9NiwxG', 3);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Gertruda', 'Teape', 'gteapej@nyu.edu', 'ha8qv4xUpGow', 2);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Karly', 'Starr', 'kstarrk@istockphoto.com', 'KoZNf7ANz', 2);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Saunder', 'Neubigin', 'sneubiginl@chronoengine.com', 'sSLJojgHony', 3);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Emelen', 'Cowap', 'ecowapm@icio.us', 'CJy4hfMPfck', 1);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Hunter', 'Tomich', 'htomichn@blogtalkradio.com', 'KhY68qsQ', 1);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Donica', 'Stein', 'dsteino@upenn.edu', 'OLJlumV1b', 3);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Simone', 'Madgwich', 'smadgwichp@usda.gov', 'YscD1tEmNcxX', 3);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Garvey', 'McNirlan', 'gmcnirlanq@house.gov', 'UumOo4sp0', 1);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Abe', 'Blasi', 'ablasir@plala.or.jp', 'kBv8KCn7PT', 3);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Margit', 'Curdell', 'mcurdells@disqus.com', 'RLvVHZu', 3);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Martguerita', 'Derrick', 'mderrickt@washington.edu', 'IiDaKZOWJ', 1);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Gertie', 'Napolitano', 'gnapolitanou@tmall.com', 'jKpy9v', 2);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Bel', 'Jamary', 'bjamaryv@xing.com', 'wwDtiJ4LlkBW', 1);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Ninon', 'Standley', 'nstandleyw@livejournal.com', 'YWei5NGMmp2e', 3);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Goraud', 'Wilne', 'gwilnex@samsung.com', '7ysU7uUH0q', 3);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Sheelagh', 'Texton', 'stextony@walmart.com', 'EkDgGVS', 2);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Lou', 'Folbigg', 'lfolbiggz@oakley.com', 'x67aj2wL3v', 3);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Kasey', 'Smidmore', 'ksmidmore10@scientificamerican.com', 'MKaisO', 1);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Brunhilda', 'McDugal', 'bmcdugal11@pagesperso-orange.fr', 'o3ejsD', 1);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Hiram', 'Masterton', 'hmasterton12@nps.gov', 'En5qhiO', 1);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Maurita', 'Drage', 'mdrage13@nba.com', 'HUlVwn3', 3);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Shandee', 'Wrightim', 'swrightim14@a8.net', '36PmeYU9H0F', 2);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Cindra', 'Kubu', 'ckubu15@adobe.com', 'gCpjyuxiCX3U', 1);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Elli', 'Dudgeon', 'edudgeon16@ebay.co.uk', 'brler4W', 1);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Sophronia', 'Farran', 'sfarran17@xrea.com', 'CRaEEM77lX', 1);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Rudy', 'Virgo', 'rvirgo18@addthis.com', 'nKz3PVm45WB', 2);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Barron', 'Goodram', 'bgoodram19@prweb.com', 'X7xePkp', 2);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Cassondra', 'Tregea', 'ctregea1a@google.com.br', 'wjAg0TLoP1H', 1);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Joey', 'Tomaello', 'jtomaello1b@rakuten.co.jp', '1nlH0Azy', 2);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Vivian', 'Durbin', 'vdurbin1c@dell.com', '0jXwBgp', 2);
INSERT INTO users (first_name, last_name, email, password, role_id) VALUES ('Wolfie', 'Dongles', 'wdongles1d@google.com.br', 'TOZYHi4FPA', 2);

